import { Sport, UserRole, Gender, FitnessTest, TestName, AthleteProfile, OfficialRole, OfficialProfile, Language } from './types';

export const SPORTS_LIST: Sport[] = Object.values(Sport);
export const USER_ROLES_LIST: UserRole[] = Object.values(UserRole);
export const GENDERS_LIST: Gender[] = Object.values(Gender);
export const OFFICIAL_ROLES_LIST: OfficialRole[] = Object.values(OfficialRole);

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Role Selection
    welcome_title: "Welcome to SPORTACLE",
    welcome_subtitle: "Select your role to get started.",
    role_athlete_title: "I am an Athlete",
    role_athlete_desc: "Sign up to record your performance, track progress, and get discovered.",
    role_official_title: "I am an Official / Coach",
    role_official_desc: "Register to monitor athletes, analyze data, and identify new talent.",
    login_link_prompt: "Already have an account?",
    login_link: "Log In",
    // Sign Up
    signup_athlete_title: "Athlete Registration",
    signup_subtitle: "Your journey to sporting excellence starts here.",
    signup_official_title: "Official & Coach Registration",
    signup_official_subtitle: "Access tools to manage and discover talent.",
    label_first_name: "First Name",
    label_last_name: "Last Name",
    label_dob: "Date of Birth",
    you_are_age: "You are {age} years old.",
    label_contact: "Phone or Email",
    label_email: "Email ID",
    label_gender: "Gender",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    label_sport: "Primary Sport",
    label_role_in_sport: "Role in Sport (e.g. Bowler, Goalkeeper)",
    label_language: "Preferred Language",
    label_organization: "Organization / Department",
    label_your_role: "Your Role",
    role_coach: "Coach",
    role_evaluator: "Evaluator",
    role_admin: "Admin",
    label_sport_focus: "Primary Sport Focus",
    button_back: "Back",
    button_create_account: "Create Account",
    alert_valid_dob: "Please enter a valid date of birth.",
    alert_valid_role: "Please enter your role in the sport.",
    // Header
    header_title: "SPORTACLE",
    button_logout: "Logout",
    // Athlete Dashboard
    welcome_back: "Welcome back, {name}!",
    dashboard_subtitle: "Ready to test your limits? Let's get started.",
    your_measurements: "Your Measurements",
    height: "Height",
    weight: "Weight",
    leaderboard_title: "Leaderboard",
    leaderboard_you: "You",
    leaderboard_pts: "pts",
    feedback_title: "AI-Powered Feedback",
    button_generating: "Generating...",
    button_get_feedback: "Get My Personal Feedback",
    badges_title: "Progress Badges",
    badge_first_test: "First Test",
    badge_speedster: "Speedster",
    badge_power_house: "Power House",
    // Fitness Test Card
    card_latest_value: "Latest Value",
    card_benchmark: "Benchmark",
    card_top_percentile: "Top {percentile}%",
    card_no_data: "No data recorded yet.",
    card_your_progress: "Your Progress",
    button_update_hw: "Update Height & Weight",
    button_view_instructions: "View Instructions",
    button_analyzing: "Analyzing...",
    button_record_test: "Record Test",
    analysis_feedback: "AI analysis complete. Detected {score} {unit}. Great form!",
    modal_instructions_title: "{testName} Instructions",
    modal_how_to_perform: "How to Perform",
    modal_how_to_record: "How to Record",
    modal_how_we_assess: "How We Assess",
    modal_preview_title: "Review Your Video",
    button_submit_analysis: "Submit for Analysis",
    status_na: "N/A",
    // Video Player
    video_unsupported: "Your browser does not support the video tag.",
    video_demonstration_for: "Demonstration for {title}",
    video_demo_title: "Demonstration for {testName}",
    // Modals
    aria_close_modal: "Close modal",
    button_cancel: "Cancel",
    // Coach Dashboard
    coach_dashboard_title: "Coach Dashboard",
    coach_dashboard_subtitle: "Monitor and guide your team's performance.",
    your_athletes_title: "Your Athletes",
    athlete_performance_title: "{name}'s Performance",
    button_get_ai_suggestions: "Get AI Suggestions",
    select_athlete_prompt: "Select an athlete to view their details.",
    // Official Dashboard
    official_dashboard_title: "Official Analytics Dashboard",
    official_dashboard_subtitle: "Transparent insights for nationwide talent identification.",
    distribution_by_sport_title: "Athlete Distribution by Sport",
    top_5_athletes_title: "Top 5 Athletes (Overall Percentile)",
    table_header_rank: "Rank",
    table_header_athlete: "Athlete",
    table_header_sport: "Sport",
    table_header_avg_percentile: "Avg. Percentile",
    // Management Dashboard
    management_dashboard_title: "Management Dashboard",
    management_dashboard_subtitle: "Monitor, analyze, and guide athletic talent.",
    nationwide_distribution_title: "Nationwide Athlete Distribution",
    athlete_roster_title: "Athlete Roster",
    submission_status_title: "Submission Status",
    status_verified: "Verified",
    status_last_updated: "Last updated on {date}",
    button_flag_review: "Flag for Review",
    button_approve: "Approve",
    alert_flagged_for_review: "Submission for {name} has been flagged for review.",
    alert_results_approved: "{name}'s latest results approved.",
    // Upload enhancements
    upload_or_drag: "Click to upload or drag and drop",
    upload_drag_active: "Drop the video file here",
    error_invalid_file_type: "Invalid file type. Please upload a MP4, MOV, or AVI video.",
    error_file_too_large: "File is too large. Please upload a video under {size}MB.",
    upload_status_uploading: "Uploading... {progress}%",
    upload_status_processing: "Processing...",
    upload_status_complete: "Upload complete!",
    upload_status_error: "Upload failed. Please try again.",
    // Test Names and Descriptions
    'test_name_vertical_jump': 'Vertical Jump',
    'test_desc_vertical_jump': 'Measure the height of your jump from a standing position.',
    'test_name_shuttle_run': '4x10m Shuttle Run',
    'test_desc_shuttle_run': 'Test of speed and agility, running between two points 10m apart.',
    'test_name_sit_ups': 'Sit-ups (1 min)',
    'test_desc_sit_ups': 'Maximum number of sit-ups you can perform in one minute.',
    'test_name_endurance_run': '1600m Run/Walk',
    'test_desc_endurance_run': 'Time taken to complete a 1600m run or walk.',
     // Height & Weight Entry Page
    hw_title: "Height & Weight Measurement",
    hw_subtitle: "This is a mandatory one-time setup to create your baseline profile.",
    hw_height_section_title: "Height Measurement",
    hw_weight_section_title: "Weight Measurement",
    hw_upload_height_video: "Upload Height Measurement Video",
    hw_upload_weight_video: "Upload Weight Measurement Video",
    hw_manual_entry_title: "Enter Measured Value",
    hw_label_height: "Height",
    hw_label_weight: "Weight",
    hw_unit_cm: "cm",
    hw_unit_ft: "ft",
    hw_unit_kg: "kg",
    hw_unit_lbs: "lbs",
    hw_placeholder_ft: "e.g., 5",
    hw_placeholder_in: "e.g., 9",
    hw_placeholder_cm: "e.g., 175",
    hw_placeholder_kg: "e.g., 68",
    hw_placeholder_lbs: "e.g., 150",
    button_save_continue: "Save and Continue",
    error_all_fields_required: "All fields are required. Please upload both videos and enter your measurements.",
    error_invalid_height: "Please enter a valid height (50-250 cm).",
    error_invalid_weight: "Please enter a valid weight (10-250 kg).",
    hw_instructions_title_height: "Height Measurement Instructions",
    hw_instructions_title_weight: "Weight Measurement Instructions",
    hw_instructions_perform_height: "Stand straight against a flat wall without shoes. Keep your feet together and look straight ahead. Place a flat object (like a book) on your head, parallel to the floor. Mark the point where the bottom of the object meets the wall.",
    hw_instructions_record_height: "Record a video where the camera shows your full body against the wall. The video must clearly show you placing the book on your head, making the mark, and then measuring the distance from the floor to the mark with a measuring tape. Ensure the numbers on the tape are visible.",
    hw_instructions_assess_height: "The video will be reviewed to verify correct posture, proper marking, and accurate reading of the measuring tape.",
    hw_instructions_perform_weight: "Use a digital or analog weighing scale on a flat, hard surface. Stand still in the center of the scale without shoes, with your weight distributed evenly on both feet.",
    hw_instructions_record_weight: "The video should first show the scale at zero. Then, record yourself stepping onto the scale and standing still. The camera must zoom in to clearly show the final weight reading on the scale's display.",
    hw_instructions_assess_weight: "The video is used to confirm the scale was zeroed and to verify the final weight measurement displayed.",
    // Login Page
    login_title: "Log In to Your Account",
    login_subtitle: "Welcome back! Please enter your details.",
    label_contact_login: "Email or Phone",
    button_login: "Log In",
    login_error: "Invalid credentials. Please check your email/phone and try again.",
    no_account_prompt: "Don't have an account?",
    signup_link: "Sign Up",
  },
  hi: {
    // Role Selection
    welcome_title: "स्पोर्टेकल में आपका स्वागत है",
    welcome_subtitle: "शुरू करने के लिए अपनी भूमिका चुनें।",
    role_athlete_title: "मैं एक एथलीट हूँ",
    role_athlete_desc: "अपने प्रदर्शन को रिकॉर्ड करने, प्रगति को ट्रैक करने और खोजे जाने के लिए साइन अप करें।",
    role_official_title: "मैं एक अधिकारी/कोच हूँ",
    role_official_desc: "एथलीटों की निगरानी करने, डेटा का विश्लेषण करने और नई प्रतिभा की पहचान करने के लिए पंजीकरण करें।",
    login_link_prompt: "पहले से ही एक खाता है?",
    login_link: "लॉग इन करें",
    // Sign Up
    signup_athlete_title: "एथलीट पंजीकरण",
    signup_subtitle: "खेल में उत्कृष्टता की आपकी यात्रा यहाँ से शुरू होती है।",
    signup_official_title: "अधिकारी और कोच पंजीकरण",
    signup_official_subtitle: "प्रतिभा का प्रबंधन और खोज करने के लिए उपकरणों तक पहुँचें।",
    label_first_name: "पहला नाम",
    label_last_name: "अंतिम नाम",
    label_dob: "जन्म की तारीख",
    you_are_age: "आप {age} वर्ष के हैं।",
    label_contact: "फोन या ईमेल",
    label_email: "ईमेल आईडी",
    label_gender: "लिंग",
    gender_male: "पुरुष",
    gender_female: "महिला",
    gender_other: "अन्य",
    label_sport: "प्राथमिक खेल",
    label_role_in_sport: "खेल में भूमिका (जैसे गेंदबाज, गोलकीपर)",
    label_language: "पसंदीदा भाषा",
    label_organization: "संगठन/विभाग",
    label_your_role: "आपकी भूमिका",
    role_coach: "कोच",
    role_evaluator: "मूल्यांकनकर्ता",
    role_admin: "एडमिन",
    label_sport_focus: "प्राथमिक खेल फोकस",
    button_back: "वापस",
    button_create_account: "खाता बनाएं",
    alert_valid_dob: "कृपया एक वैध जन्म तिथि दर्ज करें।",
    alert_valid_role: "कृपया खेल में अपनी भूमिका दर्ज करें।",
    // Header
    header_title: "स्पोर्टेकल",
    button_logout: "लॉग आउट",
    // Athlete Dashboard
    welcome_back: "वापस स्वागत है, {name}!",
    dashboard_subtitle: "अपनी सीमाओं का परीक्षण करने के लिए तैयार हैं? चलिए शुरू करते हैं।",
    your_measurements: "आपके माप",
    height: "ऊंचाई",
    weight: "वजन",
    leaderboard_title: "लीडरबोर्ड",
    leaderboard_you: "आप",
    leaderboard_pts: "अंक",
    feedback_title: "एआई-संचालित फीडबैक",
    button_generating: "उत्पन्न हो रहा है...",
    button_get_feedback: "मेरी व्यक्तिगत प्रतिक्रिया प्राप्त करें",
    badges_title: "प्रगति बैज",
    badge_first_test: "पहला टेस्ट",
    badge_speedster: "स्पीडस्टर",
    badge_power_house: "पावर हाउस",
    // Fitness Test Card
    card_latest_value: "नवीनतम मान",
    card_benchmark: "बेंचमार्क",
    card_top_percentile: "शीर्ष {percentile}%",
    card_no_data: "अभी तक कोई डेटा रिकॉर्ड नहीं किया गया है।",
    card_your_progress: "आपकी प्रगति",
    button_update_hw: "ऊंचाई और वजन अपडेट करें",
    button_view_instructions: "निर्देश देखें",
    button_analyzing: "विश्लेषण हो रहा है...",
    button_record_test: "टेस्ट रिकॉर्ड करें",
    analysis_feedback: "एआई विश्लेषण पूरा हुआ। {score} {unit} का पता चला। बढ़िया फॉर्म!",
    modal_instructions_title: "{testName} निर्देश",
    modal_how_to_perform: "कैसे प्रदर्शन करें",
    modal_how_to_record: "कैसे रिकॉर्ड करें",
    modal_how_we_assess: "हम कैसे मूल्यांकन करते हैं",
    modal_preview_title: "अपने वीडियो की समीक्षा करें",
    button_submit_analysis: "विश्लेषण के लिए सबमिट करें",
    status_na: "लागू नहीं",
    // Video Player
    video_unsupported: "आपका ब्राउज़र वीडियो टैग का समर्थन नहीं करता है।",
    video_demonstration_for: "{title} के लिए प्रदर्शन",
    video_demo_title: "{testName} के लिए प्रदर्शन",
    // Modals
    aria_close_modal: "मोडल बंद करें",
    button_cancel: "रद्द करें",
    // Coach Dashboard
    coach_dashboard_title: "कोच डैशबोर्ड",
    coach_dashboard_subtitle: "अपनी टीम के प्रदर्शन की निगरानी और मार्गदर्शन करें।",
    your_athletes_title: "आपके एथलीट",
    athlete_performance_title: "{name} का प्रदर्शन",
    button_get_ai_suggestions: "एआई सुझाव प्राप्त करें",
    select_athlete_prompt: "विवरण देखने के लिए एक एथलीट चुनें।",
     // Official Dashboard
    official_dashboard_title: "आधिकारिक एनालिटिक्स डैशबोर्ड",
    official_dashboard_subtitle: "राष्ट्रव्यापी प्रतिभा पहचान के लिए पारदर्शी अंतर्दृष्टि।",
    distribution_by_sport_title: "खेल के अनुसार एथलीट वितरण",
    top_5_athletes_title: "शीर्ष 5 एथलीट (समग्र पर्सेंटाइल)",
    table_header_rank: "रैंक",
    table_header_athlete: "एथलीट",
    table_header_sport: "खेल",
    table_header_avg_percentile: "औसत पर्सेंटाइल",
    // Management Dashboard
    management_dashboard_title: "प्रबंधन डैशबोर्ड",
    management_dashboard_subtitle: "एथलेटिक प्रतिभा की निगरानी, विश्लेषण और मार्गदर्शन करें।",
    nationwide_distribution_title: "राष्ट्रव्यापी एथलीट वितरण",
    athlete_roster_title: "एथलीट रोस्टर",
    submission_status_title: "सबमिशन स्थिति",
    status_verified: "सत्यापित",
    status_last_updated: "{date} को अंतिम बार अपडेट किया गया",
    button_flag_review: "समीक्षा के लिए ध्वज",
    button_approve: "स्वीकृत करें",
    alert_flagged_for_review: "{name} के लिए सबमिशन समीक्षा के लिए ध्वजांकित किया गया है।",
    alert_results_approved: "{name} के नवीनतम परिणाम स्वीकृत।",
    // Upload enhancements
    upload_or_drag: "अपलोड करने के लिए क्लिक करें या खींचकर छोड़ें",
    upload_drag_active: "वीडियो फ़ाइल को यहाँ छोड़ें",
    error_invalid_file_type: "अमान्य फ़ाइल प्रकार। कृपया एक MP4, MOV, या AVI वीडियो अपलोड करें।",
    error_file_too_large: "फ़ाइल बहुत बड़ी है। कृपया {size}MB से कम का वीडियो अपलोड करें।",
    upload_status_uploading: "अपलोड हो रहा है... {progress}%",
    upload_status_processing: "प्रसंस्करण हो रहा है...",
    upload_status_complete: "अपलोड पूरा हुआ!",
    upload_status_error: "अपलोड विफल। कृपया पुन: प्रयास करें।",
    // Test Names and Descriptions
    'test_name_vertical_jump': 'खड़ी कूद',
    'test_desc_vertical_jump': 'खड़ी स्थिति से अपनी कूद की ऊंचाई मापें।',
    'test_name_shuttle_run': '4x10 मीटर शटल रन',
    'test_desc_shuttle_run': 'गति और चपलता का परीक्षण, 10 मीटर की दूरी पर दो बिंदुओं के बीच दौड़ना।',
    'test_name_sit_ups': 'सिट-अप (1 मिनट)',
    'test_desc_sit_ups': 'एक मिनट में आप जितने सिट-अप कर सकते हैं, उनकी अधिकतम संख्या।',
    'test_name_endurance_run': '1600 मीटर दौड़/पैदल चलना',
    'test_desc_endurance_run': '1600 मीटर की दौड़ या पैदल चलने को पूरा करने में लगने वाला समय।',
     // Height & Weight Entry Page
    hw_title: "ऊंचाई और वजन मापन",
    hw_subtitle: "यह आपकी आधारभूत प्रोफ़ाइल बनाने के लिए एक अनिवार्य एकमुश्त सेटअप है।",
    hw_height_section_title: "ऊंचाई मापन",
    hw_weight_section_title: "वजन मापन",
    hw_upload_height_video: "ऊंचाई मापन वीडियो अपलोड करें",
    hw_upload_weight_video: "वजन मापन वीडियो अपलोड करें",
    hw_manual_entry_title: "मापा गया मान दर्ज करें",
    hw_label_height: "ऊंचाई",
    hw_label_weight: "वजन",
    hw_unit_cm: "सेमी",
    hw_unit_ft: "फीट",
    hw_unit_kg: "किग्रा",
    hw_unit_lbs: "पाउंड",
    hw_placeholder_ft: "उदा., 5",
    hw_placeholder_in: "उदा., 9",
    hw_placeholder_cm: "उदा., 175",
    hw_placeholder_kg: "उदा., 68",
    hw_placeholder_lbs: "उदा., 150",
    button_save_continue: "सहेजें और जारी रखें",
    error_all_fields_required: "सभी फ़ील्ड आवश्यक हैं। कृपया दोनों वीडियो अपलोड करें और अपने माप दर्ज करें।",
    error_invalid_height: "कृपया एक वैध ऊंचाई दर्ज करें (50-250 सेमी)।",
    error_invalid_weight: "कृपया एक वैध वजन दर्ज करें (10-250 किग्रा)।",
    hw_instructions_title_height: "ऊंचाई मापने के निर्देश",
    hw_instructions_title_weight: "वजन मापने के निर्देश",
    hw_instructions_perform_height: "बिना जूते के एक सपाट दीवार के खिलाफ सीधे खड़े हो जाएं। अपने पैरों को एक साथ रखें और सीधे आगे देखें। अपने सिर पर एक सपाट वस्तु (जैसे किताब) रखें, जो फर्श के समानांतर हो। उस बिंदु को चिह्नित करें जहां वस्तु का निचला भाग दीवार से मिलता है।",
    hw_instructions_record_height: "एक वीडियो रिकॉर्ड करें जिसमें कैमरा दीवार के खिलाफ आपके पूरे शरीर को दिखाए। वीडियो में आपको अपने सिर पर किताब रखते हुए, निशान बनाते हुए, और फिर फर्श से निशान तक की दूरी को मापने वाले टेप से मापते हुए स्पष्ट रूप से दिखाना चाहिए। सुनिश्चित करें कि टेप पर संख्याएँ दिखाई दे रही हैं।",
    hw_instructions_assess_height: "सही मुद्रा, उचित अंकन, और मापने वाले टेप की सटीक रीडिंग को सत्यापित करने के लिए वीडियो की समीक्षा की जाएगी।",
    hw_instructions_perform_weight: "एक सपाट, कठोर सतह पर एक डिजिटल या एनालॉग वजन पैमाने का उपयोग करें। जूते के बिना पैमाने के केंद्र में स्थिर खड़े रहें, अपने वजन को दोनों पैरों पर समान रूप से वितरित करें।",
    hw_instructions_record_weight: "वीडियो में पहले पैमाने को शून्य पर दिखाना चाहिए। फिर, खुद को पैमाने पर चढ़ते और स्थिर खड़े होते हुए रिकॉर्ड करें। कैमरे को पैमाने के डिस्प्ले पर अंतिम वजन रीडिंग को स्पष्ट रूप से दिखाने के लिए ज़ूम इन करना होगा।",
    hw_instructions_assess_weight: "वीडियो का उपयोग यह पुष्टि करने के लिए किया जाता है कि पैमाना शून्य था और प्रदर्शित अंतिम वजन माप को सत्यापित करने के लिए।",
    // Login Page
    login_title: "अपने खाते में लॉग इन करें",
    login_subtitle: "वापस स्वागत है! कृपया अपना विवरण दर्ज करें।",
    label_contact_login: "ईमेल या फ़ोन",
    button_login: "लॉग इन करें",
    login_error: "अमान्य क्रेडेंशियल। कृपया अपना ईमेल/फोन जांचें और पुनः प्रयास करें।",
    no_account_prompt: "खाता नहीं है?",
    signup_link: "साइन अप करें",
  },
  ta: {
    // Role Selection
    welcome_title: "ஸ்போர்ட்டக்கிள்-க்கு வரவேற்கிறோம்",
    welcome_subtitle: "தொடங்குவதற்கு உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்.",
    role_athlete_title: "நான் ஒரு விளையாட்டு வீரர்",
    role_athlete_desc: "உங்கள் செயல்திறனைப் பதிவு செய்யவும், முன்னேற்றத்தைக் கண்காணிக்கவும், கண்டறியப்படவும் பதிவு செய்யவும்.",
    role_official_title: "நான் ஒரு அதிகாரி / பயிற்சியாளர்",
    role_official_desc: "விளையாட்டு வீரர்களைக் கண்காணிக்கவும், தரவை பகுப்பாய்வு செய்யவும், புதிய திறமைகளைக் கண்டறியவும் பதிவு செய்யவும்.",
    login_link_prompt: "ஏற்கனவே கணக்கு உள்ளதா?",
    login_link: "உள்நுழையவும்",
    // Sign Up
    signup_athlete_title: "விளையாட்டு வீரர் பதிவு",
    signup_subtitle: "விளையாட்டில் உங்கள் சிறந்த பயணத்தை இங்கே தொடங்குங்கள்.",
    signup_official_title: "அதிகாரி மற்றும் பயிற்சியாளர் பதிவு",
    signup_official_subtitle: "திறமைகளை நிர்வகிக்கவும் கண்டறியவும் கருவிகளை அணுகவும்.",
    label_first_name: "முதல் பெயர்",
    label_last_name: "கடைசி பெயர்",
    label_dob: "பிறந்த தேதி",
    you_are_age: "உங்களுக்கு {age} வயது.",
    label_contact: "தொலைபேசி அல்லது மின்னஞ்சல்",
    label_email: "மின்னஞ்சல் முகவரி",
    label_gender: "பாலினம்",
    gender_male: "ஆண்",
    gender_female: "பெண்",
    gender_other: "மற்றவை",
    label_sport: "முதன்மை விளையாட்டு",
    label_role_in_sport: "விளையாட்டில் பங்கு (எ.கா. பந்துவீச்சாளர், கோல்கீப்பர்)",
    label_language: "விருப்ப மொழி",
    label_organization: "அமைப்பு / துறை",
    label_your_role: "உங்கள் பங்கு",
    role_coach: "பயிற்சியாளர்",
    role_evaluator: "மதிப்பீட்டாளர்",
    role_admin: "நிர்வாகி",
    label_sport_focus: "முதன்மை விளையாட்டு கவனம்",
    button_back: "பின்செல்",
    button_create_account: "கணக்கை உருவாக்கு",
    alert_valid_dob: "தயவுசெய்து சரியான பிறந்த தேதியை உள்ளிடவும்.",
    alert_valid_role: "தயவுசெய்து விளையாட்டில் உங்கள் பங்கை உள்ளிடவும்.",
    // Header
    header_title: "ஸ்போர்ட்டக்கிள்",
    button_logout: "வெளியேறு",
    // Athlete Dashboard
    welcome_back: "மீண்டும் வருக, {name}!",
    dashboard_subtitle: "உங்கள் வரம்புகளை சோதிக்க தயாரா? தொடங்குவோம்.",
    your_measurements: "உங்கள் அளவீடுகள்",
    height: "உயரம்",
    weight: "எடை",
    leaderboard_title: "முன்னிலை பட்டியல்",
    leaderboard_you: "நீங்கள்",
    leaderboard_pts: "புள்ளிகள்",
    feedback_title: "AI-இயங்கும் பின்னூட்டம்",
    button_generating: "உருவாக்குகிறது...",
    button_get_feedback: "எனது தனிப்பட்ட பின்னூட்டத்தைப் பெறுங்கள்",
    badges_title: "முன்னேற்றப் பதக்கங்கள்",
    badge_first_test: "முதல் சோதனை",
    badge_speedster: "ஸ்பீட்ஸ்டர்",
    badge_power_house: "பவர் ஹவுஸ்",
    // Fitness Test Card
    card_latest_value: "சமீபத்திய மதிப்பு",
    card_benchmark: "அளவுகோல்",
    card_top_percentile: "மேல் {percentile}%",
    card_no_data: "இன்னும் தரவு பதிவு செய்யப்படவில்லை.",
    card_your_progress: "உங்கள் முன்னேற்றம்",
    button_update_hw: "உயரம் மற்றும் எடையைப் புதுப்பிக்கவும்",
    button_view_instructions: "வழிமுறைகளைக் காண்க",
    button_analyzing: "பகுப்பாய்வு செய்கிறது...",
    button_record_test: "சோதனையைப் பதிவு செய்",
    analysis_feedback: "AI பகுப்பாய்வு முடிந்தது. {score} {unit} கண்டறியப்பட்டது. சிறந்த வடிவம்!",
    modal_instructions_title: "{testName} வழிமுறைகள்",
    modal_how_to_perform: "எப்படி செய்வது",
    modal_how_to_record: "எப்படி பதிவு செய்வது",
    modal_how_we_assess: "நாங்கள் எப்படி மதிப்பிடுகிறோம்",
    modal_preview_title: "உங்கள் வீடியோவை மதிப்பாய்வு செய்யவும்",
    button_submit_analysis: "பகுப்பாய்வுக்குச் சமர்ப்பிக்கவும்",
    status_na: "பொருந்தாது",
    // Video Player
    video_unsupported: "உங்கள் உலாவி வீடியோ குறிச்சொல்லை ஆதரிக்கவில்லை.",
    video_demonstration_for: "{title} க்கான செயல்விளக்கம்",
    video_demo_title: "{testName} க்கான செயல்விளக்கம்",
    // Modals
    aria_close_modal: "சாளரத்தை மூடு",
    button_cancel: "ரத்துசெய்",
    // Coach Dashboard
    coach_dashboard_title: "பயிற்சியாளர் டாஷ்போர்டு",
    coach_dashboard_subtitle: "உங்கள் அணியின் செயல்திறனைக் கண்காணித்து வழிகாட்டவும்.",
    your_athletes_title: "உங்கள் விளையாட்டு வீரர்கள்",
    athlete_performance_title: "{name} இன் செயல்திறன்",
    button_get_ai_suggestions: "AI பரிந்துரைகளைப் பெறுங்கள்",
    select_athlete_prompt: "விவரங்களைக் காண ஒரு விளையாட்டு வீரரைத் தேர்ந்தெடுக்கவும்.",
     // Official Dashboard
    official_dashboard_title: "அதிகாரப்பூர்வ பகுப்பாய்வு டாஷ்போர்டு",
    official_dashboard_subtitle: "நாடு தழுவிய திறமை கண்டறிதலுக்கான வெளிப்படையான நுண்ணறிவு.",
    distribution_by_sport_title: "விளையாட்டின் அடிப்படையில் தடகள வீரர் விநியோகம்",
    top_5_athletes_title: "சிறந்த 5 விளையாட்டு வீரர்கள் (ஒட்டுமொத்த சதவீதம்)",
    table_header_rank: "தரம்",
    table_header_athlete: "விளையாட்டு வீரர்",
    table_header_sport: "விளையாட்டு",
    table_header_avg_percentile: "சராசரி சதவீதம்",
    // Management Dashboard
    management_dashboard_title: "மேலாண்மை டாஷ்போர்டு",
    management_dashboard_subtitle: "தடகள திறமைகளைக் கண்காணிக்கவும், பகுப்பாய்வு செய்யவும் மற்றும் வழிகாட்டவும்.",
    nationwide_distribution_title: "நாடு தழுவிய தடகள வீரர் விநியோகம்",
    athlete_roster_title: "தடகள வீரர் பட்டியல்",
    submission_status_title: "சமர்ப்பிப்பு நிலை",
    status_verified: "சரிபார்க்கப்பட்டது",
    status_last_updated: "{date} அன்று கடைசியாகப் புதுப்பிக்கப்பட்டது",
    button_flag_review: "மதிப்பாய்வுக்குக் கொடியிடு",
    button_approve: "ஒப்புக்கொள்",
    alert_flagged_for_review: "{name} க்கான சமர்ப்பிப்பு மதிப்பாய்வுக்குக் கொடியிடப்பட்டுள்ளது.",
    alert_results_approved: "{name} இன் சமீபத்திய முடிவுகள் அங்கீகரிக்கப்பட்டன.",
    // Upload enhancements
    upload_or_drag: "பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
    upload_drag_active: "வீடியோ கோப்பை இங்கே விடுங்கள்",
    error_invalid_file_type: "தவறான கோப்பு வகை. தயவுசெய்து ஒரு MP4, MOV, அல்லது AVI வீடியோவைப் பதிவேற்றவும்.",
    error_file_too_large: "கோப்பு அளவு பெரியது. தயவுசெய்து {size}MB-க்கு கீழ் உள்ள வீடியோவைப் பதிவேற்றவும்.",
    upload_status_uploading: "பதிவேற்றுகிறது... {progress}%",
    upload_status_processing: "செயலாக்கப்படுகிறது...",
    upload_status_complete: "பதிவேற்றம் முடிந்தது!",
    upload_status_error: "பதிவேற்றம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
     // Test Names and Descriptions
    'test_name_vertical_jump': 'செங்குத்து লাফ',
    'test_desc_vertical_jump': 'நிற்கும் நிலையில் இருந்து உங்கள் தாவலின் உயரத்தை அளவிடவும்.',
    'test_name_shuttle_run': '4x10மீ ஷட்டில் ரன்',
    'test_desc_shuttle_run': 'வேகம் மற்றும் சுறுசுறுப்பு சோதனை, 10 மீ தொலைவில் உள்ள இரண்டு புள்ளிகளுக்கு இடையில் ஓடுதல்.',
    'test_name_sit_ups': 'சிட்-அப்ஸ் (1 நிமிடம்)',
    'test_desc_sit_ups': 'ஒரு நிமிடத்தில் உங்களால் செய்யக்கூடிய சிட்-அப்களின் அதிகபட்ச எண்ணிக்கை.',
    'test_name_endurance_run': '1600மீ ஓட்டம்/நடை',
    'test_desc_endurance_run': '1600மீ ஓட்டம் அல்லது நடையை முடிக்க ஆகும் நேரம்.',
    // Height & Weight Entry Page
    hw_title: "உயரம் மற்றும் எடை அளவீடு",
    hw_subtitle: "இது உங்கள் அடிப்படை சுயவிவரத்தை உருவாக்க ஒரு கட்டாய ஒரு முறை அமைப்பு.",
    hw_height_section_title: "உயர அளவீடு",
    hw_weight_section_title: "எடை அளவீடு",
    hw_upload_height_video: "உயர அளவீட்டு வீடியோவை பதிவேற்றவும்",
    hw_upload_weight_video: "எடை அளவீட்டு வீடியோவை பதிவேற்றவும்",
    hw_manual_entry_title: "அளவிடப்பட்ட மதிப்பை உள்ளிடவும்",
    hw_label_height: "உயரம்",
    hw_label_weight: "எடை",
    hw_unit_cm: "செமீ",
    hw_unit_ft: "அடி",
    hw_unit_kg: "கிகி",
    hw_unit_lbs: "பவுண்ட்",
    hw_placeholder_ft: "எ.கா., 5",
    hw_placeholder_in: "எ.கா., 9",
    hw_placeholder_cm: "எ.கா., 175",
    hw_placeholder_kg: "எ.கா., 68",
    hw_placeholder_lbs: "எ.கா., 150",
    button_save_continue: "சேமித்து தொடரவும்",
    error_all_fields_required: "அனைத்து புலங்களும் தேவை. தயவுசெய்து இரண்டு வீடியோக்களையும் பதிவேற்றி உங்கள் அளவீடுகளை உள்ளிடவும்.",
    error_invalid_height: "தயவுசெய்து சரியான உயரத்தை உள்ளிடவும் (50-250 செமீ).",
    error_invalid_weight: "தயவுசெய்து சரியான எடையை உள்ளிடவும் (10-250 கிகி).",
    hw_instructions_title_height: "உயரம் அளவிடும் வழிமுறைகள்",
    hw_instructions_title_weight: "எடை அளவிடும் வழிமுறைகள்",
    hw_instructions_perform_height: "காலணிகள் இல்லாமல் ஒரு தட்டையான சுவருக்கு எதிராக நேராக நிற்கவும். உங்கள் கால்களை ஒன்றாக வைத்து நேராகப் பார்க்கவும். ஒரு தட்டையான பொருளை (ஒரு புத்தகம் போல) உங்கள் தலையில், தரைக்கு இணையாக வைக்கவும். பொருளின் அடிப்பகுதி சுவரை சந்திக்கும் இடத்தைக் குறிக்கவும்.",
    hw_instructions_record_height: "சுவருக்கு எதிராக உங்கள் முழு உடலையும் காட்டும் ஒரு வீடியோவைப் பதிவு செய்யவும். வீடியோவில் நீங்கள் புத்தகத்தை உங்கள் தலையில் வைப்பதையும், குறியை உருவாக்குவதையும், பின்னர் தரையிலிருந்து குறிக்கு உள்ள தூரத்தை அளவிடும் நாடா மூலம் அளவிடுவதையும் தெளிவாகக் காட்ட வேண்டும். நாடாவில் உள்ள எண்கள் தெரிவதை உறுதிப்படுத்தவும்.",
    hw_instructions_assess_height: "சரியான தோரணை, சரியான குறித்தல் மற்றும் அளவிடும் நாடாவின் துல்லியமான வாசிப்பைச் சரிபார்க்க வீடியோ மதிப்பாய்வு செய்யப்படும்.",
    hw_instructions_perform_weight: "ஒரு தட்டையான, கடினமான மேற்பரப்பில் டிஜஜிட்டல் அல்லது அனலாக் எடை அளவைப் பயன்படுத்தவும். காலணிகள் இல்லாமல், உங்கள் எடை இரண்டு கால்களிலும் சமமாக விநியோகிக்கப்பட்டு, அளவின் மையத்தில் அசையாமல் நிற்கவும்.",
    hw_instructions_assess_weight: "அளவு பூஜ்ஜியத்தில் உள்ளதா என்பதை உறுதிப்படுத்தவும், அளவின் காட்சியில் இறுதி எடை அளவைச் சரிபார்க்கவும் வீடியோ பயன்படுத்தப்படுகிறது.",
    // Login Page
    login_title: "உங்கள் கணக்கில் உள்நுழையவும்",
    login_subtitle: "மீண்டும் வருக! உங்கள் விவரங்களை உள்ளிடவும்.",
    label_contact_login: "மின்னஞ்சல் அல்லது தொலைபேசி",
    button_login: "உள்நுழையவும்",
    login_error: "தவறான சான்றுகள். உங்கள் மின்னஞ்சல்/தொலைபேசியைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    no_account_prompt: "கணக்கு இல்லையா?",
    signup_link: "பதிவு செய்யவும்",
  },
  te: {
    // Role Selection
    welcome_title: "స్పోర్టాకిల్‌కు స్వాగతం",
    welcome_subtitle: "ప్రారంభించడానికి మీ పాత్రను ఎంచుకోండి.",
    role_athlete_title: "నేను ఒక అథ్లెట్",
    role_athlete_desc: "మీ పనితీరును రికార్డ్ చేయడానికి, పురోగతిని ట్రాక్ చేయడానికి మరియు కనుగొనబడటానికి సైన్ అప్ చేయండి.",
    role_official_title: "నేను ఒక అధికారి / కోచ్",
    role_official_desc: "అథ్లెట్లను పర్యవేక్షించడానికి, డేటాను విశ్లేషించడానికి మరియు కొత్త ప్రతిభను గుర్తించడానికి నమోదు చేసుకోండి.",
    login_link_prompt: "ఇప్పటికే ఖాతా ఉందా?",
    login_link: "లాగిన్ అవ్వండి",
    // Sign Up
    signup_athlete_title: "అథ్లెట్ నమోదు",
    signup_subtitle: "క్రీడలలో మీ उत्कृष्टता ప్రయాణం ఇక్కడ ప్రారంభమవుతుంది.",
    signup_official_title: "అధికారి మరియు కోచ్ నమోదు",
    signup_official_subtitle: "ప్రతిభను నిర్వహించడానికి మరియు కనుగొనడానికి సాధనాలను యాక్సెస్ చేయండి.",
    label_first_name: "మొదటి పేరు",
    label_last_name: "చివరి పేరు",
    label_dob: "పుట్టిన తేది",
    you_are_age: "మీ వయస్సు {age} సంవత్సరాలు.",
    label_contact: "ఫోన్ లేదా ఇమెయిల్",
    label_email: "ఇమెయిల్ ఐడి",
    label_gender: "లింగం",
    gender_male: "పురుషుడు",
    gender_female: "స్త్రీ",
    gender_other: "ఇతర",
    label_sport: "ప్రాథమిక క్రీడ",
    label_role_in_sport: "క్రీడలో పాత్ర (ఉదా. బౌలర్, గోల్ కీపర్)",
    label_language: "ఇష్టపడే భాష",
    label_organization: "సంస్థ / విభాగం",
    label_your_role: "మీ పాత్ర",
    role_coach: "కోచ్",
    role_evaluator: "మూల్యాంకనం చేసేవారు",
    role_admin: "అడ్మిన్",
    label_sport_focus: "ప్రాథమిక క్రీడ ఫోకస్",
    button_back: "వెనుకకు",
    button_create_account: "ఖాతాను సృష్టించండి",
    alert_valid_dob: "దయచేసి సరైన పుట్టిన తేదీని నమోదు చేయండి.",
    alert_valid_role: "దయచేసి క్రీడలో మీ పాత్రను నమోదు చేయండి.",
    // Header
    header_title: "స్పోర్టాకిల్",
    button_logout: "లాగ్ అవుట్",
    // Athlete Dashboard
    welcome_back: "తిరిగి స్వాగతం, {name}!",
    dashboard_subtitle: "మీ పరిమితులను పరీక్షించడానికి సిద్ధంగా ఉన్నారా? ప్రారంభిద్దాం.",
    your_measurements: "మీ కొలతలు",
    height: "ఎత్తు",
    weight: "బరువు",
    leaderboard_title: "లీడర్‌బోర్డ్",
    leaderboard_you: "మీరు",
    leaderboard_pts: "పాయింట్లు",
    feedback_title: "AI-ఆధారిత అభిప్రాయం",
    button_generating: "సృష్టిస్తోంది...",
    button_get_feedback: "నా వ్యక్తిగత అభిప్రాయాన్ని పొందండి",
    badges_title: "పురోగతి బ్యాడ్జ్‌లు",
    badge_first_test: "మొదటి పరీక్ష",
    badge_speedster: "స్పీడ్‌స్టర్",
    badge_power_house: "పవర్ హౌస్",
    // Fitness Test Card
    card_latest_value: "తాజా విలువ",
    card_benchmark: "బెంచ్‌మార్క్",
    card_top_percentile: "టాప్ {percentile}%",
    card_no_data: "ఇంకా డేటా రికార్డ్ చేయబడలేదు.",
    card_your_progress: "మీ పురోగతి",
    button_update_hw: "ఎత్తు & బరువును నవీకరించండి",
    button_view_instructions: "సూచనలను వీక్షించండి",
    button_analyzing: "విశ్లేషిస్తోంది...",
    button_record_test: "పరీక్షను రికార్డ్ చేయండి",
    analysis_feedback: "AI విశ్లేషణ పూర్తయింది. {score} {unit} కనుగొనబడింది. గొప్ప ఫారం!",
    modal_instructions_title: "{testName} సూచనలు",
    modal_how_to_perform: "ఎలా ప్రదర్శించాలి",
    modal_how_to_record: "ఎలా రికార్డ్ చేయాలి",
    modal_how_we_assess: "మేము ఎలా అంచనా వేస్తాము",
    modal_preview_title: "మీ వీడియోను సమీక్షించండి",
    button_submit_analysis: "విశ్లేషణ కోసం సమర్పించండి",
    status_na: "వర్తించదు",
    // Video Player
    video_unsupported: "మీ బ్రౌజర్ వీడియో ట్యాగ్‌కు మద్దతు ఇవ్వదు.",
    video_demonstration_for: "{title} కోసం ప్రదర్శన",
    video_demo_title: "{testName} కోసం ప్రదర్శన",
    // Modals
    aria_close_modal: "మోడల్‌ను మూసివేయండి",
    button_cancel: "రద్దు చేయండి",
    // Coach Dashboard
    coach_dashboard_title: "కోచ్ డాష్‌బోర్డ్",
    coach_dashboard_subtitle: "మీ బృందం పనితీరును పర్యవేక్షించండి మరియు మార్గనిర్దేశం చేయండి.",
    your_athletes_title: "మీ అథ్లెట్లు",
    athlete_performance_title: "{name} పనితీరు",
    button_get_ai_suggestions: "AI సూచనలను పొందండి",
    select_athlete_prompt: "వివరాలను వీక్షించడానికి ఒక అథ్లెట్‌ను ఎంచుకోండి.",
     // Official Dashboard
    official_dashboard_title: "అధికారిక విశ్లేషణల డాష్‌బోర్డ్",
    official_dashboard_subtitle: "దేశవ్యాప్త ప్రతిభ గుర్తింపు కోసం పారదర్శక అంతర్దృష్టులు.",
    distribution_by_sport_title: "క్రీడల వారీగా అథ్లెట్ల పంపిణీ",
    top_5_athletes_title: "టాప్ 5 అథ్లెట్లు (మొత్తం పర్సంటైల్)",
    table_header_rank: "ర్యాంక్",
    table_header_athlete: "అథ్లెట్",
    table_header_sport: "క్రీడ",
    table_header_avg_percentile: "సగటు పర్సంటైల్",
    // Management Dashboard
    management_dashboard_title: "నిర్వహణ డాష్‌బోర్డ్",
    management_dashboard_subtitle: "అథ్లెటిక్ ప్రతిభను పర్యవేక్షించండి, విశ్లేషించండి మరియు మార్గనిర్దేశం చేయండి.",
    nationwide_distribution_title: "దేశవ్యాప్త అథ్లెట్ల పంపిణీ",
    athlete_roster_title: "అథ్లెట్ రోస్టర్",
    submission_status_title: "సమర్పణ స్థితి",
    status_verified: "ధృవీకరించబడింది",
    status_last_updated: "{date} న చివరిగా నవీకరించబడింది",
    button_flag_review: "సమీక్ష కోసం ఫ్లాగ్ చేయండి",
    button_approve: "ఆమోదించండి",
    alert_flagged_for_review: "{name} కోసం సమర్పణ సమీక్ష కోసం ఫ్లాగ్ చేయబడింది.",
    alert_results_approved: "{name} యొక్క తాజా ఫలితాలు ఆమోదించబడ్డాయి.",
    // Upload enhancements
    upload_or_drag: "అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి లేదా లాగి వదలండి",
    upload_drag_active: "వీడియో ఫైల్‌ను ఇక్కడ వదలండి",
    error_invalid_file_type: "చెల్లని ఫైల్ రకం. దయచేసి MP4, MOV, లేదా AVI వీడియోను అప్‌లోడ్ చేయండి.",
    error_file_too_large: "ఫైల్ పరిమాణం చాలా పెద్దది. దయచేసి {size}MB కంటే తక్కువ ఉన్న వీడియోను అప్‌లోడ్ చేయండి.",
    upload_status_uploading: "అప్‌లోడ్ చేస్తోంది... {progress}%",
    upload_status_processing: "ప్రాసెస్ చేస్తోంది...",
    upload_status_complete: "అప్‌లోడ్ పూర్తయింది!",
    upload_status_error: "అప్‌లోడ్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    // Test Names and Descriptions
    'test_name_vertical_jump': 'నిలువు జంప్',
    'test_desc_vertical_jump': 'నిలబడి ఉన్న స్థానం నుండి మీ జంప్ యొక్క ఎత్తును కొలవండి.',
    'test_name_shuttle_run': '4x10మీ షటిల్ రన్',
    'test_desc_shuttle_run': 'వేగం మరియు చురుకుదనం యొక్క పరీక్ష, 10 మీటర్ల దూరంలో ఉన్న రెండు పాయింట్ల మధ్య పరుగెత్తడం.',
    'test_name_sit_ups': 'సిట్-అప్స్ (1 నిమిషం)',
    'test_desc_sit_ups': 'ఒక నిమిషంలో మీరు చేయగల గరిష్ట సిట్-అప్‌ల సంఖ్య.',
    'test_name_endurance_run': '1600మీ పరుగు/నడక',
    'test_desc_endurance_run': '1600మీ పరుగు లేదా నడకను పూర్తి చేయడానికి తీసుకున్న సమయం.',
    // Height & Weight Entry Page
    hw_title: "ఎత్తు & బరువు కొలత",
    hw_subtitle: "ఇది మీ బేస్‌లైన్ ప్రొఫైల్‌ను సృష్టించడానికి తప్పనిసరి ఒక-முறை సెటప్.",
    hw_height_section_title: "ఎత్తు కొలత",
    hw_weight_section_title: "బరువు కొలత",
    hw_upload_height_video: "ఎత్తు కొలత వీడియోను అప్‌లోడ్ చేయండి",
    hw_upload_weight_video: "బరువు కొలత వీడియోను అప్‌లోడ్ చేయండి",
    hw_manual_entry_title: "కొలవబడిన విలువను నమోదు చేయండి",
    hw_label_height: "ఎత్తు",
    hw_label_weight: "బరువు",
    hw_unit_cm: "సెం.మీ",
    hw_unit_ft: "అడుగులు",
    hw_unit_kg: "కిలోలు",
    hw_unit_lbs: "పౌండ్లు",
    hw_placeholder_ft: "ఉదా., 5",
    hw_placeholder_in: "ఉదా., 9",
    hw_placeholder_cm: "ఉదా., 175",
    hw_placeholder_kg: "ఉదా., 68",
    hw_placeholder_lbs: "ఉదా., 150",
    button_save_continue: "సేవ్ చేసి కొనసాగించండి",
    error_all_fields_required: "అన్ని ఫీల్డ్‌లు అవసరం. దయచేసి రెండు వీడియోలను అప్‌లోడ్ చేయండి మరియు మీ కొలతలను నమోదు చేయండి.",
    error_invalid_height: "దయచేసి చెల్లుబాటు అయ్యే ఎత్తును నమోదు చేయండి (50-250 సెం.మీ).",
    error_invalid_weight: "దయచేసి చెల్లుబాటు అయ్యే బరువును నమోదు చేయండి (10-250 కిలోలు).",
    hw_instructions_title_height: "ఎత్తు కొలత సూచనలు",
    hw_instructions_title_weight: "బరువు కొలత సూచనలు",
    hw_instructions_perform_height: "బూట్లు లేకుండా ఒక ఫ్లాట్ గోడకు వ్యతిరేకంగా నిటారుగా నిలబడండి. మీ పాదాలను కలిపి ఉంచి, నేరుగా ముందుకు చూడండి. మీ తలపై ఒక ఫ్లాట్ వస్తువును (పుస్తకం వంటివి) నేలకు సమాంతరంగా ఉంచండి. వస్తువు దిగువ భాగం గోడను కలిసే చోట గుర్తు పెట్టండి.",
    hw_instructions_record_height: "కెమెరా గోడకు వ్యతిరేకంగా మీ పూర్తి శరీరాన్ని చూపే వీడియోను రికార్డ్ చేయండి. వీడియోలో మీరు మీ తలపై పుస్తకాన్ని ఉంచడం, గుర్తు పెట్టడం, ఆపై నేల నుండి గుర్తుకు ఉన్న దూరాన్ని కొలిచే టేప్‌తో కొలవడం స్పష్టంగా చూపాలి. టేప్‌లోని సంఖ్యలు కనిపించేలా చూసుకోండి.",
    hw_instructions_assess_height: "సరైన భంగిమ, సరైన మార్కింగ్ మరియు కొలిచే టేప్ యొక్క ఖచ్చితమైన పఠనాన్ని ధృవీకరించడానికి వీడియో సమీక్షించబడుతుంది.",
    hw_instructions_perform_weight: "ఒక ఫ్లాట్, గట్టి ఉపరితలంపై డిజిటల్ లేదా అనలాగ్ బరువు తూచే యంత్రాన్ని ఉపయోగించండి. బూట్లు లేకుండా, మీ బరువు రెండు పాదాలపై సమానంగా పంపిణీ చేయబడి, స్కేల్ మధ్యలో నిశ్చలంగా నిలబడండి.",
    hw_instructions_record_weight: "వీడియో మొదట స్కేల్‌ను సున్నా వద్ద చూపాలి. అప్పుడు, మీరు స్కేల్‌పైకి ఎక్కి నిశ్చలంగా నిలబడటాన్ని రికార్డ్ చేయండి. కెమెరా స్కేల్ డిస్‌ప్లేపై తుది బరువు పఠనాన్ని స్పష్టంగా చూపించడానికి జూమ్ చేయాలి.",
    hw_instructions_assess_weight: "స్కేల్ సున్నా చేయబడిందని నిర్ధారించడానికి మరియు ప్రదర్శించబడిన తుది బరువు కొలతను ధృవీకరించడానికి వీడియో ఉపయోగించబడుతుంది.",
    // Login Page
    login_title: "మీ ఖాతాలోకి లాగిన్ అవ్వండి",
    login_subtitle: "తిరిగి స్వాగతం! దయచేసి మీ వివరాలను నమోదు చేయండి.",
    label_contact_login: "ఇమెయిల్ లేదా ఫోన్",
    button_login: "లాగిన్ అవ్వండి",
    login_error: "చెల్లని ఆధారాలు. దయచేసి మీ ఇమెయిల్/ఫోన్‌ను తనిఖీ చేసి, మళ్లీ ప్రయత్నించండి.",
    no_account_prompt: "ఖాతా లేదా?",
    signup_link: "నమోదు చేసుకోండి",
  },
};

export const FITNESS_TESTS: FitnessTest[] = [
  { 
    id: 't2', 
    name: TestName.VERTICAL_JUMP, 
    descriptionKey: "test_desc_vertical_jump", 
    videoUrl: "https://videos.pexels.com/video-files/5840507/5840507-hd_1920_1080_30fps.mp4", 
    unit: "cm",
    instructions: {
      en: {
        perform: "Stand beside a wall and reach up as high as you can with one hand, marking the point. Then, from a standing start, jump as high as you can and mark the new height. The difference is your score.",
        record: "Record a side-view video that clearly shows your standing reach, the peak of your jump, and the measurement of the distance between the two marks.",
        assess: "Performance is assessed based on the measured height difference and proper jumping technique (e.g., no running start)."
      },
      hi: {
        perform: "एक दीवार के बगल में खड़े हो जाओ और एक हाथ से जितना हो सके उतना ऊपर पहुंचें, उस बिंदु को चिह्नित करें। फिर, एक स्थिर शुरुआत से, जितना हो सके उतना ऊंचा कूदें और नई ऊंचाई को चिह्नित करें। अंतर आपका स्कोर है।",
        record: "एक साइड-व्यू वीडियो रिकॉर्ड करें जो स्पष्ट रूप से आपकी खड़ी पहुंच, आपकी कूद की चोटी, और दो निशानों के बीच की दूरी का माप दिखाता है।",
        assess: "प्रदर्शन का मूल्यांकन मापी गई ऊंचाई के अंतर और उचित कूदने की तकनीक (जैसे, कोई दौड़ने की शुरुआत नहीं) के आधार पर किया जाता है।"
      },
      ta: {
        perform: "ஒரு சுவரின் அருகில் நின்று, ஒரு கையால் எவ்வளவு முடியுமோ அவ்வளவு உயரத்திற்குச் சென்று, அந்த இடத்தைக் குறிக்கவும். பின்னர், நின்ற நிலையில் இருந்து, உங்களால் முடிந்தவரை உயரமாக குதித்து புதிய உயரத்தைக் குறிக்கவும். வித்தியாசம் உங்கள் மதிப்பெண்.",
        record: "உங்கள் நிற்கும் நிலை, உங்கள் தாவலின் உச்சம் மற்றும் இரண்டு மதிப்பெண்களுக்கு இடையே உள்ள தூரத்தின் அளவீடு ஆகியவற்றை தெளிவாகக் காட்டும் பக்கப் பார்வை வீடியோவைப் பதிவு செய்யவும்.",
        assess: "செயல்திறன் அளவிடப்பட்ட உயர வேறுபாடு மற்றும் சரியான ஜம்பிங் நுட்பத்தின் அடிப்படையில் மதிப்பிடப்படுகிறது (எ.கா., ஓடும் ஆரம்பம் இல்லை).",
      },
      te: {
        perform: "గోడ పక్కన నిలబడి, ఒక చేత్తో మీకు వీలైనంత ఎత్తుకు చేరుకుని, ఆ స్థానాన్ని గుర్తించండి. అప్పుడు, నిలబడి ఉన్నప్పటి నుండి, మీకు వీలైనంత ఎత్తుకు దూకి, కొత్త ఎత్తును గుర్తించండి. వ్యత్యాసం మీ స్కోరు.",
        record: "మీ నిలబడి ఉన్నప్పటి ఎత్తు, మీ జంప్ యొక్క శిఖరం మరియు రెండు మార్కుల మధ్య దూరం యొక్క కొలతను స్పష్టంగా చూపే సైడ్-వ్యూ వీడియోను రికార్డ్ చేయండి.",
        assess: "పనితీరు కొలిచిన ఎత్తు వ్యత్యాసం మరియు సరైన జంపింగ్ టెక్నిక్ (ఉదా., రన్నింగ్ స్టార్ట్ లేదు) ఆధారంగా అంచనా వేయబడుతుంది.",
      }
    }
  },
  { 
    id: 't3', 
    name: TestName.SHUTTLE_RUN, 
    descriptionKey: "test_desc_shuttle_run", 
    videoUrl: "https://videos.pexels.com/video-files/8097127/8097127-sd_640_360_24fps.mp4", 
    unit: "s",
    instructions: {
      en: {
        perform: "Set two markers 10 meters apart. Start at one marker, run to the other, touch the line, and return. Repeat this twice (4 lengths in total). Time the entire run.",
        record: "The camera should be positioned to see both markers. The video must clearly show you touching each line and include a visible stopwatch or timer from start to finish.",
        assess: "Your score is the total time taken. Assessment also considers if the lines were touched correctly on each turn."
      },
      hi: {
        perform: "10 मीटर की दूरी पर दो मार्कर सेट करें। एक मार्कर से शुरू करें, दूसरे तक दौड़ें, लाइन को छुएं, और वापस आएं। इसे दो बार दोहराएं (कुल 4 लंबाई)। पूरे रन का समय लें।",
        record: "कैमरे को दोनों मार्करों को देखने के लिए तैनात किया जाना चाहिए। वीडियो में आपको प्रत्येक पंक्ति को छूते हुए स्पष्ट रूप से दिखाना चाहिए और शुरू से अंत तक एक दृश्य स्टॉपवॉच या टाइमर शामिल होना चाहिए।",
        assess: "आपका स्कोर लिया गया कुल समय है। मूल्यांकन यह भी विचार करता है कि क्या प्रत्येक मोड़ पर लाइनों को सही ढंग से छुआ गया था।"
      },
      ta: {
        perform: "10 மீட்டர் இடைவெளியில் இரண்டு குறிப்பான்களை அமைக்கவும். ஒரு மார்க்கரில் தொடங்கி, மற்றொன்றுக்கு ஓடி, கோட்டைத் தொட்டு, திரும்பவும். இதை இரண்டு முறை செய்யவும் (மொத்தம் 4 நீளங்கள்). முழு ஓட்டத்தையும் நேரம் ஒதுக்குங்கள்.",
        record: "கேமரா இரண்டு குறிப்பான்களையும் பார்க்கும் வகையில் நிலைநிறுத்தப்பட வேண்டும். ஒவ்வொரு வரியையும் நீங்கள் தொடுவதை வீடியோ தெளிவாகக் காட்ட வேண்டும் மற்றும் தொடக்கத்திலிருந்து இறுதி வரை தெரியும் ஸ்டாப்வாட்ச் அல்லது டைமரைச் சேர்க்க வேண்டும்.",
        assess: "உங்கள் மதிப்பெண் எடுக்கப்பட்ட மொத்த நேரம். ஒவ்வொரு திருப்பத்திலும் கோடுகள் சரியாகத் தொடப்பட்டதா என்பதையும் மதிப்பீடு கருதுகிறது."
      },
      te: {
        perform: "10 మీటర్ల దూరంలో రెండు మార్కర్లను సెట్ చేయండి. ఒక మార్కర్ వద్ద ప్రారంభించండి, మరొకదానికి పరుగెత్తండి, గీతను తాకి, తిరిగి రండి. దీన్ని రెండుసార్లు పునరావృతం చేయండి (మొత్తం 4 పొడవులు). మొత్తం పరుగును సమయం చేయండి.",
        record: "కెమెరా రెండు మార్కర్‌లను చూసే విధంగా ఉంచాలి. వీడియో మీరు ప్రతి గీతను తాకడాన్ని స్పష్టంగా చూపించాలి మరియు ప్రారంభం నుండి ముగింపు వరకు కనిపించే స్టాప్‌వాచ్ లేదా టైమర్‌ను కలిగి ఉండాలి.",
        assess: "మీ స్కోరు తీసుకున్న మొత్తం సమయం. ప్రతి మలుపులో పంక్తులు సరిగ్గా తాకినాయా అని కూడా అంచనా పరిగణిస్తుంది."
      }
    }
  },
  { 
    id: 't4', 
    name: TestName.SIT_UPS, 
    descriptionKey: "test_desc_sit_ups", 
    videoUrl: "https://videos.pexels.com/video-files/5225477/5225477-hd_1920_1080_25fps.mp4", 
    unit: "reps",
    instructions: {
      en: {
        perform: "Lie on your back with knees bent. Have someone hold your feet or place them under a stable object. Place hands on opposite shoulders. Raise your upper body to touch your elbows to your knees and return to the floor. Count reps in 1 minute.",
        record: "Record a side-view video showing your full range of motion for the entire minute. A timer must be visible in the frame.",
        assess: "The score is the number of correctly performed sit-ups. A rep is counted only if elbows touch knees and shoulders return to the floor."
      },
      hi: {
        perform: "घुटनों को मोड़कर अपनी पीठ के बल लेट जाएं। किसी से अपने पैर पकड़वाएं या उन्हें किसी स्थिर वस्तु के नीचे रखें। हाथों को विपरीत कंधों पर रखें। अपने ऊपरी शरीर को अपनी कोहनी को अपने घुटनों से छूने के लिए उठाएं और फर्श पर लौट आएं। 1 मिनट में प्रतिनिधि गिनें।",
        record: "पूरे मिनट के लिए अपनी गति की पूरी श्रृंखला दिखाते हुए एक साइड-व्यू वीडियो रिकॉर्ड करें। फ्रेम में एक टाइमर दिखाई देना चाहिए।",
        assess: "स्कोर सही ढंग से किए गए सिट-अप्स की संख्या है। एक प्रतिनिधि तभी गिना जाता है जब कोहनी घुटनों को छूती है और कंधे फर्श पर लौट आते हैं।"
      },
      ta: {
        perform: "முழங்கால்களை வளைத்து உங்கள் முதுகில் படுத்துக் கொள்ளுங்கள். யாராவது உங்கள் கால்களைப் பிடிக்கச் செய்யுங்கள் அல்லது அவற்றை ஒரு நிலையான பொருளின் கீழ் வைக்கவும். கைகளை எதிர் தோள்களில் வைக்கவும். உங்கள் முழங்கைகளை உங்கள் முழங்கால்களில் தொடுவதற்கு உங்கள் மேல் உடலை உயர்த்தி, தரையில் திரும்பவும். 1 நிமிடத்தில் பிரதிநிதிகளை எண்ணுங்கள்.",
        record: "முழு நிமிடத்திற்கும் உங்கள் முழு அளவிலான இயக்கத்தைக் காட்டும் பக்கப் பார்வை வீடியோவைப் பதிவுசெய்யவும். சட்டகத்தில் ஒரு டைமர் தெரிய வேண்டும்.",
        assess: "சரியாகச் செய்யப்பட்ட சிட்-அப்களின் எண்ணிக்கை மதிப்பெண். முழங்கைகள் முழங்கால்களைத் தொட்டு, தோள்கள் தரைக்குத் திரும்பினால் மட்டுமே ஒரு பிரதிநிதி கணக்கிடப்படுவார்."
      },
      te: {
        perform: "మోకాళ్లను వంచి మీ వెనుక పడుకోండి. ఎవరైనా మీ పాదాలను పట్టుకోండి లేదా స్థిరమైన వస్తువు కింద ఉంచండి. చేతులను ఎదురుగా ఉన్న భుజాలపై ఉంచండి. మీ మోచేతులను మీ మోకాళ్లకు తాకడానికి మీ పై శరీరాన్ని పైకి లేపి, నేలపైకి తిరిగి వెళ్లండి. 1 నిమిషంలో రెప్స్ లెక్కించండి.",
        record: "మొత్తం నిమిషం పాటు మీ పూర్తి స్థాయి కదలికను చూపే సైడ్-వ్యూ వీడియోను రికార్డ్ చేయండి. ఫ్రేమ్‌లో టైమర్ తప్పనిసరిగా కనిపించాలి.",
        assess: "స్కోరు సరిగ్గా ప్రదర్శించిన సిట్-అప్‌ల సంఖ్య. మోచేతులు మోకాళ్లను తాకి, భుజాలు నేలపైకి తిరిగి వస్తే మాత్రమే రెప్ లెక్కించబడుతుంది."
      }
    }
  },
  { 
    id: 't5', 
    name: TestName.ENDURANCE_RUN, 
    descriptionKey: "test_desc_endurance_run", 
    videoUrl: "https://videos.pexels.com/video-files/857041/857041-hd_1920_1080_25fps.mp4", 
    unit: "min",
    instructions: {
      en: {
        perform: "Run or walk a 1600-meter distance (e.g., 4 laps on a standard 400m track) as fast as you can. Record your total time.",
        record: "The video should show the start of the run, the final lap, and the finish line crossing. A timer or stopwatch must be clearly visible.",
        assess: "Your score is the total time in minutes and seconds. The video is used to verify the distance covered and the recorded time."
      },
      hi: {
        perform: "1600-मीटर की दूरी (जैसे, एक मानक 400 मीटर ट्रैक पर 4 लैप्स) जितनी जल्दी हो सके दौड़ें या चलें। अपना कुल समय रिकॉर्ड करें।",
        record: "वीडियो में दौड़ की शुरुआत, अंतिम लैप और फिनिश लाइन क्रॉसिंग दिखनी चाहिए। एक टाइमर या स्टॉपवॉच स्पष्ट रूप से दिखाई देनी चाहिए।",
        assess: "आपका स्कोर मिनटों और सेकंडों में कुल समय है। वीडियो का उपयोग तय की गई दूरी और रिकॉर्ड किए गए समय को सत्यापित करने के लिए किया जाता है।"
      },
      ta: {
        perform: "1600 மீட்டர் தூரத்தை (எ.கா., ஒரு நிலையான 400 மீ பாதையில் 4 சுற்றுகள்) உங்களால் முடிந்தவரை வேகமாக ஓடவும் அல்லது நடக்கவும். உங்கள் மொத்த நேரத்தைப் பதிவு செய்யுங்கள்.",
        record: "வீடியோ ஓட்டத்தின் ஆரம்பம், இறுதி சுற்று மற்றும் финиш கோட்டைக் கடப்பதைக் காட்ட வேண்டும். ஒரு டைமர் அல்லது ஸ்டॉपவாட்ச் தெளிவாகத் தெரிய வேண்டும்.",
        assess: "உங்கள் மதிப்பெண் நிமிடங்கள் மற்றும் வினாடிகளில் மொத்த நேரம். கடந்து வந்த தூரம் மற்றும் பதிவு செய்யப்பட்ட நேரத்தைச் சரிபார்க்க வீடியோ பயன்படுத்தப்படுகிறது."
      },
      te: {
        perform: "1600-మీటర్ల దూరం (ఉదా., ప్రామాణిక 400 మీ ట్రాక్‌పై 4 ల్యాప్‌లు) వీలైనంత వేగంగా పరుగెత్తండి లేదా నడవండి. మీ మొత్తం సమయాన్ని రికార్డ్ చేయండి.",
        record: "వీడియో పరుగు ప్రారంభం, చివరి ల్యాప్ మరియు ముగింపు రేఖ దాటడాన్ని చూపాలి. టైమర్ లేదా స్టాప్‌వాచ్ స్పష్టంగా కనిపించాలి.",
        assess: "మీ స్కోరు నిమిషాలు మరియు సెకన్లలో మొత్తం సమయం. కవర్ చేయబడిన దూరం మరియు రికార్డ్ చేయబడిన సమయాన్ని ధృవీకరించడానికి వీడియో ఉపయోగించబడుతుంది."
      }
    }
  },
];

export const MOCK_ATHLETES: AthleteProfile[] = [
  {
    id: 'athlete1',
    firstName: 'Priya',
    lastName: 'Sharma',
    dob: '2008-05-15',
    contact: 'priya.sharma@email.com',
    sport: Sport.ATHLETICS,
    role: UserRole.ATHLETE,
    roleInSport: 'Sprinter',
    age: 16,
    gender: Gender.FEMALE,
    language: 'en',
    heightWeight: {
        height: 165,
        heightUnit: 'cm',
        weight: 58,
        weightUnit: 'kg',
        heightVideoUrl: '',
        weightVideoUrl: ''
    },
    results: [
      { testId: 't2', latestScore: 45, benchmark: 40, percentile: 75, history: [{ date: '2024-06-01', value: 42 }, { date: '2024-07-15', value: 45 }] },
      { testId: 't3', latestScore: 11.5, benchmark: 12.0, percentile: 80, history: [{ date: '2024-06-01', value: 11.8 }, { date: '2024-07-15', value: 11.5 }] },
      { testId: 't4', latestScore: 42, benchmark: 38, percentile: 85, history: [{ date: '2024-06-01', value: 38 }, { date: '2024-07-15', value: 42 }] },
      { testId: 't5', latestScore: 7.5, benchmark: 8.0, percentile: 78, history: [{ date: '2024-06-01', value: 7.8 }, { date: '2024-07-15', value: 7.5 }] },
    ]
  },
  {
    id: 'athlete2',
    firstName: 'Rohan',
    lastName: 'Verma',
    dob: '2007-11-20',
    contact: 'rohan.verma@email.com',
    sport: Sport.CRICKET,
    role: UserRole.ATHLETE,
    roleInSport: 'Batsman',
    age: 17,
    gender: Gender.MALE,
    language: 'hi',
     heightWeight: {
        height: 178,
        heightUnit: 'cm',
        weight: 72,
        weightUnit: 'kg',
        heightVideoUrl: '',
        weightVideoUrl: ''
    },
    results: [
      { testId: 't2', latestScore: 55, benchmark: 58, percentile: 65, history: [{ date: '2024-05-20', value: 53 }, { date: '2024-07-10', value: 55 }] },
      { testId: 't3', latestScore: 11.2, benchmark: 11.5, percentile: 70, history: [{ date: '2024-05-20', value: 11.4 }, { date: '2024-07-10', value: 11.2 }] },
      { testId: 't4', latestScore: 50, benchmark: 45, percentile: 90, history: [{ date: '2024-05-20', value: 46 }, { date: '2024-07-10', value: 50 }] },
      { testId: 't5', latestScore: 6.8, benchmark: 7.2, percentile: 82, history: [{ date: '2024-05-20', value: 7.0 }, { date: '2024-07-10', value: 6.8 }] },
    ]
  },
  {
    id: 'athlete3',
    firstName: 'Aisha',
    lastName: 'Khan',
    dob: '2009-02-10',
    contact: 'aisha.khan@email.com',
    sport: Sport.BASKETBALL,
    role: UserRole.ATHLETE,
    roleInSport: 'Point Guard',
    age: 15,
    gender: Gender.FEMALE,
    language: 'en',
    heightWeight: {
        height: 170,
        heightUnit: 'cm',
        weight: 60,
        weightUnit: 'kg',
        heightVideoUrl: '',
        weightVideoUrl: ''
    },
    results: [
      { testId: 't2', latestScore: 48, benchmark: 42, percentile: 88, history: [{ date: '2024-06-15', value: 46 }, { date: '2024-07-20', value: 48 }] },
      { testId: 't3', latestScore: 11.8, benchmark: 12.2, percentile: 72, history: [{ date: '2024-06-15', value: 12.0 }, { date: '2024-07-20', value: 11.8 }] },
      { testId: 't4', latestScore: 39, benchmark: 35, percentile: 80, history: [{ date: '2024-06-15', value: 36 }, { date: '2024-07-20', value: 39 }] },
      { testId: 't5', latestScore: 7.9, benchmark: 8.3, percentile: 68, history: [{ date: '2024-06-15', value: 8.1 }, { date: '2024-07-20', value: 7.9 }] },
    ]
  }
];

export const MOCK_COACH_USER: OfficialProfile = {
  id: 'coach1',
  firstName: 'Vikram',
  lastName: 'Singh',
  dob: '1985-03-22',
  contact: 'vikram.singh@email.com',
  sport: Sport.HOCKEY,
  role: UserRole.COACH,
  officialRole: OfficialRole.COACH,
  organization: 'Regional Sports Academy',
  age: 39,
  gender: Gender.MALE,
  language: 'en',
};

export const MOCK_OFFICIAL_USER: OfficialProfile = {
    id: 'official1',
    firstName: 'Anjali',
    lastName: 'Mehta',
    dob: '1980-09-12',
    contact: 'anjali.mehta@sai.gov.in',
    sport: Sport.ATHLETICS,
    role: UserRole.OFFICIAL,
    officialRole: OfficialRole.EVALUATOR,
    organization: 'Sports Authority of India',
    age: 43,
    gender: Gender.FEMALE,
    language: 'en',
};